#开发环境配置

server:
  # 服务端口
  port: 5000


spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url: jdbc:mysql://localhost:3306/missyou?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root


# 开启权限拦截
auth:
  enabled: true


# 开启http请求日志记录
request-log:
  enabled: true


logging:
  level:
    # web信息日志记录
    web: debug
    # SQL日志记录
    io.github.talelin.latticy.mapper: debug

lin:
  file:
    qiniuyun:
      access-key: beUAuJY13OuvnaJtvX-PJ00I3DYpgtDSetsB-aVj
      secret-key: _SD1ffvMjJa967Ag5EAfRLgAa04HFJv8ObbL3Lcj
      bucket: _SD1ffvMjJa967Ag5EAfRLgAa04HFJv8ObbL3Lcj




